### ISSUE TITLE
ERROR: Plot axis not defined: y

### ISSUE THREAD

**Issue by ferrojm** [blobtoolkit/core#11]
Hi! 
I created my genome dir and when trying to plot the blob by default, it asks to define the 'y axis'
Am I making some mistake? 
The other plots went perfect!

my command:
blobtk plot -v blob -d genome_dir -o blob_plot.png

the error:
ERROR: Plot axis not defined: y

thanks!

**Comment by ferrojm** [comment]
It was my fault that I did not add the bam file for coverage.
I'm very sorry.

**Comment by Euphrasiologist** [comment]
@rjchallis I think this error message could be more informative though?
